[workspace]
members = [
  "lowering/base",
  "lowering/rows",
  "types/base",
  "types/items",
  "types/rows", 
]

[workspace.dependencies]
types-base = { path = "types/base" }
types-rows = { path = "types/rows" }
ena = "0.14.2"
im = "15.1"
pretty_assertions = "1.4"

[package]
name = "type-inference"
version = "0.1.0"
edition = "2021"
