[workspace]
members = [
  "lowering/base",
  "types/base",
  "types/items",
  "types/rows", 
]

[workspace.dependencies]
types-base = { path = "types/base" }
ena = "0.14.2"
im = "15.1"
pretty_assertions = "1.4"
expect-test = "1.5.1"
pretty = "0.12.3"

[package]
name = "type-inference"
version = "0.1.0"
edition = "2021"
