[package]
name = "making-a-language"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
  "types/base",
  "types/items",
  "types/rows",
  "lowering/base",
  "lowering/rows",
  "lowering/items",
  "simplify/base",
  "monomorph/base",
  "closure_convert/base", 
  "emit/base", 
  "parser/base", 
  "desugar/base",
  "name_resolution/base", 
  "compiler/base",
]

[workspace.package]
edition = "2024"

[workspace.dependencies]
types-base = { path = "types/base" }
types-rows = { path = "types/rows" }
types-items = { path = "types/items" }
lowering-base = { path = "lowering/base" }
lowering-rows = { path = "lowering/rows" }
simplify-base = { path = "simplify/base" }
monomorph-base = { path = "monomorph/base" }
closure-convert-base = { path = "closure_convert/base" }
emit-base = { path = "emit/base" }
parser-base = { path = "parser/base" }
desugar-base = { path = "desugar/base" }
name-resolution-base = { path = "name_resolution/base" }
compiler-base = { path = "compiler/base" }

ena = "0.14.2"
expect-test = "1.5.1"
im = "15.1"
parking_lot = { version = "0.12" }
pretty_assertions = "1.4"
pretty = "0.12.3"
wasmtime = "34" 
wasmprinter = "0.238"
wasmparser = { version = "0.238", features = ["validate", "features"] }
wast = "238"

[dependencies]
parser-base.workspace = true
desugar-base.workspace = true
name-resolution-base.workspace = true
types-base.workspace = true
lowering-base.workspace = true
simplify-base.workspace = true
monomorph-base.workspace = true
closure-convert-base.workspace = true
emit-base.workspace = true
